SELECT FR.PRODUCT_ID, FR.PRODUCT_NAME, TEMP.AMOUNT * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS FR
    INNER JOIN 
    (
        SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT, PRODUCE_DATE
        FROM FOOD_ORDER
        WHERE PRODUCE_DATE LIKE '2022-05%'
        GROUP BY PRODUCT_ID
    ) AS TEMP
    ON FR.PRODUCT_ID = TEMP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FR.PRODUCT_ID